import {StyleSheet} from 'react-native';

const getStyles = visibleOption =>
  StyleSheet.create({
    overlay1: {
      // flex: 1,
      zIndex: visibleOption.basicOption,
      position: 'absolute',
      width: '100%',
      height: '100%',
      backgroundColor: 'rgba(0, 0, 0, 0.36)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    overlay2: {
      // flex: 1,
      zIndex: visibleOption.takeoutOption,
      position: 'absolute',
      width: '100%',
      height: '100%',
      backgroundColor: 'rgba(0, 0, 0, 0.36)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    overlay_order: {
      // flex: 1,
      zIndex: visibleOption.order,
      position: 'absolute',
      width: '100%',
      height: '100%',
      backgroundColor: 'rgba(0, 0, 0, 0.36)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    overlay_payment: {
      // flex: 1,
      zIndex: visibleOption.payment,
      position: 'absolute',
      width: '100%',
      height: '100%',
      backgroundColor: 'rgba(0, 0, 0, 0.36)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    overlay_pay: {
      // flex: 1,
      zIndex: visibleOption.pay,
      position: 'absolute',
      width: '100%',
      height: '100%',
      backgroundColor: 'rgba(0, 0, 0, 0.36)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    overlay_final: {
      zIndex: visibleOption.final,
      position: 'absolute',
      width: '100%',
      height: '100%',
      backgroundColor: 'rgba(0, 0, 0, 0.36)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    optionContainer: {
      width: '90%',
      height: '60%',
      zIndex: 1,
      backgroundColor: 'white',
      justifyContent: 'space-between',
    },
    optionTitle: {
      backgroundColor: '#005D2E',
      alignItems: 'center',
      justifyContent: 'center',
      height: '12.5%',
    },
    optionTitleText: {
      fontFamily: 'NanumSquare_acEB',
      fontSize: 22,
      color: 'white',
    },
    optionContents: {
      backgroundColor: 'white',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'space-evenly',
      height: '87.5%',
    },
    optionTemperature: {
      backgroundColor: 'white',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-evenly',
      width: '100%',
      height: '23%',
    },
    temperatureBtn: {
      backgroundColor: '#D3CBC0',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-evenly',
      borderRadius: 5,
      width: '35%',
      height: '100%',
    },
    temperatureBtn_S: {
      backgroundColor: '#654F43',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-evenly',
      borderRadius: 5,
      width: '35%',
      height: '100%',
    },
    optionImage_hot: {
      resizeMode: 'contain',
      width: '30%',
    },
    optionImage_ice: {
      resizeMode: 'contain',
      width: '25%',
    },
    temperature_text: {
      fontFamily: 'NanumSquare_acEB',
      fontSize: 20,
      color: 'black',
    },
    temperature_text_w: {
      fontFamily: 'NanumSquare_acEB',
      fontSize: 20,
      color: 'white',
    },
    optionSize: {
      backgroundColor: 'white',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-evenly',
      width: '100%',
      height: '42%',
    },
    sizeBtn: {
      backgroundColor: 'white',
      borderColor: 'black',
      borderWidth: 1,
      flexDirection: 'column',
      alignItems: 'center',
      //justifyContent: 'center',
      borderRadius: 5,
      width: '24.5%',
      //height: '100%',
      marginHorizontal: -25,
    },
    sizeBtn_S: {
      backgroundColor: '#654F43',
      borderColor: 'black',
      borderWidth: 1,
      flexDirection: 'column',
      alignItems: 'center',
      //justifyContent: 'center',
      borderRadius: 5,
      width: '24.5%',
      //height: '100%',
      marginHorizontal: -25,
    },
    optionImage_size_1: {
      resizeMode: 'contain',
      width: '30%',
      height: '70%',
      marginTop: -9,
    },
    optionImage_size_2: {
      resizeMode: 'contain',
      width: '35%',
      height: '70%',
      marginTop: -9,
    },
    optionImage_size_3: {
      resizeMode: 'contain',
      width: '40%',
      height: '70%',
      marginTop: -9,
    },
    size_text_1: {
      fontFamily: 'NanumSquare_acB',
      fontSize: 18,
      color: 'black',
    },
    size_text_2: {
      fontFamily: 'NanumSquare_acEB',
      fontSize: 18,
      color: '#C80000',
    },
    optionBtn: {
      backgroundColor: 'white',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-evenly',
      width: '100%',
      height: '13%',
    },
    selectBtn_1: {
      backgroundColor: 'white',
      borderColor: '#3D3D4F',
      borderWidth: 2,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 5,
      width: '35%',
      height: '100%',
    },
    selectBtn_2: {
      backgroundColor: '#3D3D4F',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 5,
      width: '35%',
      height: '100%',
    },
    cancel_text: {
      color: '#3D3D4F',
    },
    select_text: {
      color: 'white',
    },
    optionQuantity: {
      //backgroundColor: 'red',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-evenly',
      width: '100%',
      height: '10%',
    },
    munuInfo: {
      //backgroundColor: 'orange',
      marginRight: -20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    menu_text: {
      fontFamily: 'NanumSquare_acEB',
      fontSize: 22,
      color: 'black',
    },
    quantityBtn: {
      backgroundColor: 'white',
      borderRadius: 5,
      borderColor: '#654F43',
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
      width: '10%',
      height: '100%',
    },
    quantityInfo: {
      backgroundColor: 'white',
      alignItems: 'center',
      justifyContent: 'center',
      width: '12%',
      height: '100%',
      marginHorizontal: -45,
    },
    quantity_text: {
      fontFamily: 'NanumSquare_acEB',
      fontSize: 28,
      color: 'black',
    },
  });

export default getStyles;
